[package]
authors = ["mrvollger <mrvollger@gmail.com>"]
build = "build.rs"
categories = ["command-line-utilities"]
description = "Mitchell Vollger's utilities for alignments"
edition = "2018"
homepage = "https://mrvollger.github.io/rustybam/"
keywords = ["cli", "bam", "paf", "liftover"]
license = "MIT"
name = "rustybam"
readme = "README.md"
repository = "https://github.com/mrvollger/rustybam"
version = "0.1.14"

[[bin]]
name = "rb"
path = "src/main.rs"

[[bin]]
name = "rustybam"
path = "src/main.rs"

[features]
default = ["deflate_zlib_ng", "libdeflate"]

deflate_rust = ["gzp/deflate_rust", "flate2/rust_backend"]
deflate_zlib = ["gzp/deflate_zlib", "flate2/zlib", "any_zlib"]
deflate_zlib_ng = ["gzp/deflate_zlib_ng", "flate2/zlib-ng-compat", "any_zlib"]
libdeflate = ["gzp/libdeflate"]

any_zlib = [] # internal feature flag

[dependencies]
anyhow = "1.0.44"
bimap = "0.6.1"
bio = "0.34.0"
bio-types = "0.12.0"
calm_io = "0.1.1"
clap = {version = "3.0.0-beta.4", features = ["yaml"]}
colored = "2.0.0"
flate2 = {version = "~1", default-features = false}
gzp = {version = "0.8.2", default-features = false}
itertools = "0.10.0"
lazy_static = "1.4.0"
rayon = "1.5"
regex = "1.5.4"
rust-htslib = "0.36.0"

[build-dependencies]
clap = "3.0.0-beta.4"
clap_generate = "3.0.0-beta.4"
