[package]
authors = ["mrvollger <mrvollger@gmail.com>"]
build = "build.rs"
description = "Mitchell Vollger's utilities for alignments"
edition = "2018"
homepage = "https://mrvollger.github.io/rustybam/"
license = "MIT"
name = "rustybam"
readme = "README.md"
repository = "https://github.com/mrvollger/rustybam"
version = "0.1.6"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["deflate_zlib_ng", "snap_default", "libdeflate"]

deflate_rust = ["gzp/deflate_rust", "flate2/rust_backend"]
deflate_zlib = ["gzp/deflate_zlib", "flate2/zlib", "any_zlib"]
deflate_zlib_ng = ["gzp/deflate_zlib_ng", "flate2/zlib-ng-compat", "any_zlib"]
libdeflate = ["gzp/libdeflate"]
snap_default = ["gzp/snappy_default", "snap", "snappy"]

any_zlib = [] # internal feature flag
snappy = [] # internal feature flag

[dependencies]
bimap = "0.6.1"
bio = "0.34.0"
bio-types = "0.12.0"
calm_io = "0.1.1"
clap = {version = "3.0.0-beta.2", features = ["yaml"]}
colored = "2.0.0"
flate2 = {version = "~1", default-features = false}
gzp = {version = "0.8.2", default-features = false}
itertools = "0.10.0"
rayon = "1.5"
regex = "1.5.4"
rust-htslib = "0.36.0"
snap = {version = "1.0.5", optional = true}
strum = {version = "0.21.0", features = ["derive"]}
strum_macros = "0.21"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
