[package]
authors = ["mrvollger <mrvollger@gmail.com>"]
build = "build.rs"
description = "Mitchell Vollger's utilities for alignments"
edition = "2018"
homepage = "https://mrvollger.github.io/rustybam/"
license = "MIT"
name = "rustybam"
readme = "README.md"
repository = "https://github.com/mrvollger/rustybam"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bimap = "*"
bio = "*"
bio-types = "*"
calm_io = "0.1.1"
clap = {version = "3.0.0-beta.2", features = ["yaml"]}
colored = "*"
itertools = "0.10.0"
rayon = "1.5"
regex = "*"
rust-htslib = "*"

[build-dependencies]
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
